package buildjob

import (
	"flag"
	"os"
	"strings"
	"testing"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/equality"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	orkanov1alpha1 "github.com/orkanoio/orkano/api/v1alpha1"
)

var update = flag.Bool("update", false, "rewrite the golden Job manifest the substrate smoke applies")

const (
	goldenPath         = "../../../hack/ci/substrate-smoke/09-build-job-template.yaml"
	buildkitdTomlPath  = "../../../config/buildkit/buildkitd-config.yaml"
	smokeFixtureGitURL = "https://github.com/orkanoio/orkano.git#main:hack/ci/substrate-smoke/fixture"
)

const goldenHeader = `# GENERATED by operator/internal/buildjob — do not edit by hand.
# Regenerate: go test ./operator/internal/buildjob -run TestGoldenJob -update
# This is the product build Job template rendered with the smoke's inputs,
# pinned here so the substrate smoke (probe 10) runs the EXACT Job the
# operator will create: spike-F2 securityContext at PSA baseline, git-URL
# context, TLS push to the product registry through the projected CA
# (ADR-0012). The golden test fails if this file and the Go template drift.
# run.sh's apply_job can override the git context via SMOKE_GIT_CONTEXT.
`

func goldenInputs() (*orkanov1alpha1.Build, Options) {
	build := &orkanov1alpha1.Build{
		ObjectMeta: metav1.ObjectMeta{Name: "template-smoke", Namespace: "orkano-apps"},
		// 600 rather than the 900 default so the golden proves the
		// timeoutSeconds → activeDeadlineSeconds mapping with a real value.
		Spec: orkanov1alpha1.BuildSpec{TimeoutSeconds: 600},
	}
	return build, Options{
		ContextURL: smokeFixtureGitURL,
		ImageRef:   RegistryHost + "/smoke/template:fixture",
	}
}

func TestGoldenJob(t *testing.T) {
	build, opts := goldenInputs()
	job, err := Render(build, opts)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	if *update {
		out := job.DeepCopy()
		out.TypeMeta = metav1.TypeMeta{APIVersion: "batch/v1", Kind: "Job"}
		raw, err := yaml.Marshal(out)
		if err != nil {
			t.Fatalf("marshaling golden Job: %v", err)
		}
		if err := os.WriteFile(goldenPath, append([]byte(goldenHeader), raw...), 0o644); err != nil {
			t.Fatalf("writing golden file: %v", err)
		}
		return
	}

	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading golden file (regenerate with -update): %v", err)
	}
	var want batchv1.Job
	if err := yaml.Unmarshal(raw, &want); err != nil {
		t.Fatalf("decoding golden file: %v", err)
	}
	want.TypeMeta = metav1.TypeMeta{}
	if !equality.Semantic.DeepEqual(&want, job) {
		gotYAML, _ := yaml.Marshal(job)
		t.Errorf("rendered Job drifted from %s (regenerate with -update)\n--- golden:\n%s\n--- rendered:\n%s", goldenPath, raw, gotYAML)
	}
}

// The toml the build pod mounts lives in a static manifest; this pins it to
// the mount paths and registry host the template hardcodes, so the two
// cannot drift apart silently.
func TestBuildkitdConfigManifestMatchesTemplate(t *testing.T) {
	raw, err := os.ReadFile(buildkitdTomlPath)
	if err != nil {
		t.Fatalf("reading %s: %v", buildkitdTomlPath, err)
	}
	var cm corev1.ConfigMap
	if err := yaml.Unmarshal(raw, &cm); err != nil {
		t.Fatalf("decoding %s: %v", buildkitdTomlPath, err)
	}
	if cm.Name != configConfigMapName || cm.Namespace != Namespace {
		t.Errorf("ConfigMap is %s/%s, template mounts %s/%s", cm.Namespace, cm.Name, Namespace, configConfigMapName)
	}
	toml, ok := cm.Data["buildkitd.toml"]
	if !ok {
		t.Fatal("ConfigMap has no buildkitd.toml key — the template's --config path would be an empty mount")
	}
	if want := `[registry."` + RegistryHost + `"]`; !strings.Contains(toml, want) {
		t.Errorf("buildkitd.toml does not configure the canonical registry host: missing %s", want)
	}
	if want := `"` + caMountPath + `/ca.crt"`; !strings.Contains(toml, want) {
		t.Errorf("buildkitd.toml ca path does not match the template's CA mount: missing %s", want)
	}
}

func TestRenderTimeoutAndDefaults(t *testing.T) {
	build, opts := goldenInputs()
	build.Spec.TimeoutSeconds = 0
	job, err := Render(build, opts)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if got := *job.Spec.ActiveDeadlineSeconds; got != DefaultTimeoutSeconds {
		t.Errorf("zero timeoutSeconds rendered activeDeadlineSeconds %d, want the %d default", got, DefaultTimeoutSeconds)
	}
	if got := job.Spec.Template.Spec.Containers[0].Image; got != DefaultImage {
		t.Errorf("empty Options.Image rendered %q, want DefaultImage", got)
	}

	opts.Image = "mirror.example/buildkit@sha256:0000000000000000000000000000000000000000000000000000000000000000"
	job, err = Render(build, opts)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if got := job.Spec.Template.Spec.Containers[0].Image; got != opts.Image {
		t.Errorf("Options.Image override rendered %q, want %q", got, opts.Image)
	}
}

func TestRenderRejectsIncompleteInputs(t *testing.T) {
	build, opts := goldenInputs()
	for name, mutate := range map[string]func(*orkanov1alpha1.Build, *Options){
		"no build name":      func(b *orkanov1alpha1.Build, _ *Options) { b.Name = "" },
		"no build namespace": func(b *orkanov1alpha1.Build, _ *Options) { b.Namespace = "" },
		"no context URL":     func(_ *orkanov1alpha1.Build, o *Options) { o.ContextURL = "" },
		"no image ref":       func(_ *orkanov1alpha1.Build, o *Options) { o.ImageRef = "" },
	} {
		b, o := build.DeepCopy(), opts
		mutate(b, &o)
		if _, err := Render(b, o); err == nil {
			t.Errorf("%s: Render succeeded, want error", name)
		}
	}
}

func TestJobName(t *testing.T) {
	for _, tc := range []struct {
		in, want string
	}{
		{in: "template-smoke", want: "template-smoke"},
		{in: strings.Repeat("x", 63), want: strings.Repeat("x", 63)},
		{
			in:   strings.Repeat("a", 50) + "." + strings.Repeat("b", 50),
			want: strings.Repeat("a", 50) + "." + "bbb-4d7da6c8",
		},
		// The cut lands on the "."; the trim keeps the name DNS-legal.
		{
			in:   strings.Repeat("a", 53) + "." + strings.Repeat("b", 47),
			want: strings.Repeat("a", 53) + "-" + "9e5f0c1a",
		},
	} {
		got := JobName(tc.in)
		if tc.want != "" && got != tc.want {
			t.Errorf("JobName(%q) = %q, want %q", tc.in, got, tc.want)
		}
		if len(got) > 63 {
			t.Errorf("JobName(%q) is %d chars, exceeds the 63-char label limit", tc.in, len(got))
		}
	}
	if JobName(strings.Repeat("y", 64)) == JobName(strings.Repeat("y", 65)) {
		t.Error("distinct over-long names truncated to the same Job name")
	}
}
