// Package config exposes the static cluster manifests `orkano init` deploys.
// The install engine (internal/install) embeds them straight from their single
// source of truth here, so the CRDs (generated by controller-gen), namespaces,
// RBAC, NetworkPolicies, the registry, and the buildkit config never drift from
// what `kubectl apply -f config/...` and the substrate smoke apply.
//
// An embed directive cannot reach outside the directory of its source file, so
// it lives in this package (inside config/) rather than in internal/install.
// Manifests needing a per-install value — component Deployments with
// version-tagged first-party images, the generated Secrets, and node-specific
// policies — are templated by internal/install, not stored here; everything
// applied verbatim (including the digest-pinned platform Postgres) lives here.
package config

import "embed"

// StaticManifests holds the manifests deployed verbatim to every Orkano
// cluster, keyed by their path under config/ (e.g. "crd/orkano.io_apps.yaml").
// config/apparmor is deliberately excluded: it is a node-loaded profile, not a
// Kubernetes manifest.
//
//go:embed crd namespaces rbac netpol registry buildkit components cert-manager traefik
var StaticManifests embed.FS
