// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
)

const appendAuditEntry = `-- name: AppendAuditEntry :exec
INSERT INTO audit_log (actor, action, target, outcome, detail)
VALUES ($1, $2, $3, $4, COALESCE($5::jsonb, '{}'::jsonb))
`

type AppendAuditEntryParams struct {
	Actor   string
	Action  string
	Target  string
	Outcome string
	Detail  []byte
}

// INV-08: the dashboard role holds INSERT and SELECT on audit_log but never
// UPDATE or DELETE, so an entry can be added and shown but never rewritten or
// erased. The write is fire-and-forget (no RETURNING) so the audit-WRITE path
// needs only INSERT — the role's SELECT exists solely for ListAuditEntries (the
// audit view). `detail` is structured context and per INV-03 never carries a
// secret value.
func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) error {
	_, err := q.db.Exec(ctx, appendAuditEntry,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Outcome,
		arg.Detail,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, occurred_at, actor, action, target, outcome, detail
FROM audit_log
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListAuditEntriesParams struct {
	Limit  int32
	Offset int32
}

// Most-recent-first, paged by limit/offset for the audit view.
func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
