// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy_history.sql

package db

import (
	"context"
)

const listAppDeploys = `-- name: ListAppDeploys :many
SELECT id, occurred_at, app_namespace, app_name, build_name, image, status
FROM deploy_history
WHERE app_namespace = $1 AND app_name = $2
ORDER BY id DESC
LIMIT $3 OFFSET $4
`

type ListAppDeploysParams struct {
	AppNamespace string
	AppName      string
	Limit        int32
	Offset       int32
}

// The deploy timeline for one app, most-recent-first.
func (q *Queries) ListAppDeploys(ctx context.Context, arg ListAppDeploysParams) ([]DeployHistory, error) {
	rows, err := q.db.Query(ctx, listAppDeploys,
		arg.AppNamespace,
		arg.AppName,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeployHistory
	for rows.Next() {
		var i DeployHistory
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.AppNamespace,
			&i.AppName,
			&i.BuildName,
			&i.Image,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeploy = `-- name: RecordDeploy :one
INSERT INTO deploy_history (app_namespace, app_name, build_name, image, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, occurred_at, app_namespace, app_name, build_name, image, status
`

type RecordDeployParams struct {
	AppNamespace string
	AppName      string
	BuildName    string
	Image        string
	Status       string
}

// Append one event to an app's deploy timeline (image is the digest-pinned ref).
func (q *Queries) RecordDeploy(ctx context.Context, arg RecordDeployParams) (DeployHistory, error) {
	row := q.db.QueryRow(ctx, recordDeploy,
		arg.AppNamespace,
		arg.AppName,
		arg.BuildName,
		arg.Image,
		arg.Status,
	)
	var i DeployHistory
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.AppNamespace,
		&i.AppName,
		&i.BuildName,
		&i.Image,
		&i.Status,
	)
	return i, err
}
