// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WebhookDelivery struct {
	ID         int64
	DeliveryID string
	Repo       string
	EventType  string
	ReceivedAt pgtype.Timestamptz
}
