// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64
	OccurredAt pgtype.Timestamptz
	Actor      string
	Action     string
	Target     string
	Outcome    string
	Detail     []byte
}

type DeployHistory struct {
	ID           int64
	OccurredAt   pgtype.Timestamptz
	AppNamespace string
	AppName      string
	BuildName    string
	Image        string
	Status       string
}

type RecoveryCode struct {
	ID        int64
	UserID    int64
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	TokenHash  string
	UserID     int64
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ReauthAt   pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              int64
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	OidcIssuer      pgtype.Text
	OidcSubject     pgtype.Text
}

type WebhookDelivery struct {
	ID         int64
	DeliveryID string
	Repo       string
	EventType  string
	ReceivedAt pgtype.Timestamptz
	AppName    pgtype.Text
}
