// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package db

import (
	"context"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE recovery_codes
SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id
`

type ConsumeRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

// Single-use redemption: stamp used_at on a still-unused code for this user. A row
// returned means it was consumed; pgx.ErrNoRows means the code is invalid or was
// already used. The WHERE used_at IS NULL makes a replay of a spent code a no-op.
func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

// How many recovery codes remain for a user (drives a low-codes warning / forced
// regeneration).
func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

// Store one recovery code as its SHA256 hash (never plaintext). The caller hashes
// the code it showed once at enrollment.
func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}
