// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmUserTOTP = `-- name: ConfirmUserTOTP :exec
UPDATE users SET totp_confirmed_at = now(), updated_at = now() WHERE id = $1
`

// Stamp the second factor as enrolled, completing bootstrap.
func (q *Queries) ConfirmUserTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmUserTOTP, id)
	return err
}

const countConfirmedAdmins = `-- name: CountConfirmedAdmins :one
SELECT count(*) FROM users WHERE totp_confirmed_at IS NOT NULL
`

// Redemption of the install token is open only while this is 0: a confirmed admin
// (second factor enrolled) means bootstrap is done.
func (q *Queries) CountConfirmedAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfirmedAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// A coarse population count. NOTE the real bootstrap gate is CountConfirmedAdmins,
// not this — post-OIDC (00006) a JIT OIDC user counts here too, so CountUsers > 0
// no longer implies the local admin exists.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (username, password_hash, totp_secret, oidc_issuer, oidc_subject)
VALUES ($1, '', '', $2, $3)
RETURNING id, username, oidc_issuer, oidc_subject
`

type CreateOIDCUserParams struct {
	Username string
	Issuer   pgtype.Text
	Subject  pgtype.Text
}

type CreateOIDCUserRow struct {
	ID          int64
	Username    string
	OidcIssuer  pgtype.Text
	OidcSubject pgtype.Text
}

// Just-in-time provision an OIDC-linked user (ADR-0016 §5): a credential-less
// session anchor. password_hash and totp_secret are set to ” on purpose (the
// credential + MFA live at the IdP); totp_confirmed_at stays NULL so the
// single-confirmed-admin index ignores it. username holds the IdP email for
// display/audit; a collision trips the lower(username) unique index (23505).
// RETURNING is minimal — the id is all the caller needs to mint a session; read
// the full anchor via GetUserByOIDC/GetUserByID if more is ever required.
func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (CreateOIDCUserRow, error) {
	row := q.db.QueryRow(ctx, createOIDCUser, arg.Username, arg.Issuer, arg.Subject)
	var i CreateOIDCUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.OidcIssuer,
		&i.OidcSubject,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, totp_secret, totp_confirmed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, totp_secret, totp_confirmed_at, failed_logins, locked_until, created_at, updated_at
`

type CreateUserParams struct {
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
}

type CreateUserRow struct {
	ID              int64
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// The bootstrap admin (single-tenant v1). Created in one shot with the bcrypt
// hash and the TOTP seed already set — ADR-0003 admits no state where an admin
// exists without a second factor.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.TotpSecret,
		arg.TotpConfirmedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnconfirmedUsers = `-- name: DeleteUnconfirmedUsers :exec
DELETE FROM users WHERE totp_confirmed_at IS NULL AND oidc_subject IS NULL
`

// Clear an abandoned LOCAL-ADMIN enrollment (a row created but TOTP never
// confirmed) before a fresh install-token redeem. Not a bypass: the install token
// is still required per redeem attempt. An OIDC row (00006) is ALSO
// totp_confirmed_at NULL but is a permanent identity anchor, not an abandoned
// enrollment — `oidc_subject IS NULL` excludes it so a redeem never wipes an OIDC
// user (ADR-0016 §5).
func (q *Queries) DeleteUnconfirmedUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUnconfirmedUsers)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, totp_secret, totp_confirmed_at, failed_logins, locked_until, oidc_issuer, oidc_subject, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              int64
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	OidcIssuer      pgtype.Text
	OidcSubject     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// oidc_subject lets resolveSession admit an OIDC-linked row on the positive
// subject signal (ADR-0016 §6), never merely on a NULL totp_confirmed_at.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDC = `-- name: GetUserByOIDC :one
SELECT id, username, password_hash, totp_secret, totp_confirmed_at, failed_logins, locked_until, oidc_issuer, oidc_subject, created_at, updated_at
FROM users
WHERE oidc_issuer = $1 AND oidc_subject = $2
`

type GetUserByOIDCParams struct {
	Issuer  pgtype.Text
	Subject pgtype.Text
}

type GetUserByOIDCRow struct {
	ID              int64
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	OidcIssuer      pgtype.Text
	OidcSubject     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// The OIDC login lookup keyed on the real identity (issuer, subject). A hit means
// the human already has a JIT row; a miss (pgx.ErrNoRows) means provision one.
func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (GetUserByOIDCRow, error) {
	row := q.db.QueryRow(ctx, getUserByOIDC, arg.Issuer, arg.Subject)
	var i GetUserByOIDCRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, totp_secret, totp_confirmed_at, failed_logins, locked_until, oidc_issuer, oidc_subject, created_at, updated_at
FROM users
WHERE lower(username) = lower($1)
`

type GetUserByUsernameRow struct {
	ID              int64
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	OidcIssuer      pgtype.Text
	OidcSubject     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Login lookup; matched case-insensitively against the lowercased unique index.
// Returns the lockout state so the handler can refuse a locked account, plus
// oidc_subject so the password path can treat an OIDC identity like an unknown
// user (ADR-0016 §6).
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedLogins = `-- name: IncrementFailedLogins :one
UPDATE users
SET failed_logins = failed_logins + 1, updated_at = now()
WHERE id = $1
RETURNING failed_logins
`

// Bump the consecutive-failure counter on a bad attempt; returns the new count so
// the handler can lock once it crosses the threshold.
func (q *Queries) IncrementFailedLogins(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedLogins, id)
	var failed_logins int32
	err := row.Scan(&failed_logins)
	return failed_logins, err
}

const lockUser = `-- name: LockUser :exec
UPDATE users SET locked_until = $1, updated_at = now() WHERE id = $2
`

type LockUserParams struct {
	LockedUntil pgtype.Timestamptz
	UserID      int64
}

// Lock the account until @locked_until (the handler computes the deadline).
func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.LockedUntil, arg.UserID)
	return err
}

const resetFailedLogins = `-- name: ResetFailedLogins :exec
UPDATE users SET failed_logins = 0, locked_until = NULL, updated_at = now() WHERE id = $1
`

// Clear the lockout state on a successful login.
func (q *Queries) ResetFailedLogins(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetFailedLogins, id)
	return err
}
