// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// The bootstrap-completed check: zero users means the one-time install token is
// still redeemable; one or more means the local admin already exists.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, totp_secret, totp_confirmed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, totp_secret, totp_confirmed_at, created_at, updated_at
`

type CreateUserParams struct {
	Username        string
	PasswordHash    string
	TotpSecret      string
	TotpConfirmedAt pgtype.Timestamptz
}

// The bootstrap admin (single-tenant v1). Created in one shot with the bcrypt
// hash and the TOTP seed already set — ADR-0003 admits no state where an admin
// exists without a second factor.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.TotpSecret,
		arg.TotpConfirmedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, totp_secret, totp_confirmed_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, totp_secret, totp_confirmed_at, created_at, updated_at
FROM users
WHERE lower(username) = lower($1)
`

// Login lookup; matched case-insensitively against the lowercased unique index.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
