// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package db

import (
	"context"
)

const enqueueDelivery = `-- name: EnqueueDelivery :execrows
INSERT INTO webhook_deliveries (delivery_id, repo, event_type)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type EnqueueDeliveryParams struct {
	DeliveryID string
	Repo       string
	EventType  string
}

// Bare ON CONFLICT DO NOTHING, deliberately with no named arbiter: naming the
// conflict target (delivery_id) makes Postgres infer the arbiter index, which
// requires SELECT on that column — a privilege the INSERT-only receiver role
// must never hold (INV-04). delivery_id is the table's only unique constraint,
// so the bare form dedups identically while keeping the receiver INSERT-only.
func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueDelivery, arg.DeliveryID, arg.Repo, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
