// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package db

import (
	"context"
)

const enqueueDelivery = `-- name: EnqueueDelivery :execrows
INSERT INTO webhook_deliveries (delivery_id, repo, event_type)
VALUES ($1, $2, $3)
ON CONFLICT (delivery_id) DO NOTHING
`

type EnqueueDeliveryParams struct {
	DeliveryID string
	Repo       string
	EventType  string
}

func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueDelivery, arg.DeliveryID, arg.Repo, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
